/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "PGA_1.h"
#include "WaveDAC8_1.h"
#include "Speaker_Output_aliases.h"
#include "Speaker_Output.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "Comp.h"
#include "HEARTRATE_ANALOG_IN_aliases.h"
#include "HEARTRATE_ANALOG_IN.h"
#include "timer_clock_1.h"
#include "LEFT_LED_aliases.h"
#include "LEFT_LED.h"
#include "amp_aliases.h"
#include "amp.h"
#include "Compint.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "HeartbeatCounter.h"
#include "PWM.h"
#include "PWM_Output_aliases.h"
#include "PWM_Output.h"
#include "STOP_REQUEST_aliases.h"
#include "STOP_REQUEST.h"
#include "STOP.h"
#include "WDT_Timer.h"
#include "WDT.h"
#include "MOTOR_HEALTH_aliases.h"
#include "MOTOR_HEALTH.h"
#include "HEARTRATE_HEALTH_aliases.h"
#include "HEARTRATE_HEALTH.h"
#include "UI_HEALTH_aliases.h"
#include "UI_HEALTH.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

